const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });

const express = require('express');
const cors = require('cors');
const multer = require('multer');
const fs = require('fs');
const rateLimit = require('express-rate-limit');

const {
  handleDeploy, serveDeploy, listDeployments, subdomainMiddleware, streamLogs,
  deleteDeployment, listVersions, rollbackDeployment, handleGithubDeploy,
} = require('./routes/deploy');
const authRoutes = require('./routes/auth');
const store = require('./services/store');
const healthRoutes = require('./routes/health');
const requireAuth = require('./middleware/requireAuth');
const adminRoutes = require('./routes/admin');
const abuseRoutes = require('./routes/abuse');
const { isWalletSuspended, isDeploymentSuspended } = require('./services/contentPolicy');

const app = express();
const PORT = process.env.PORT || 3000;

// Trust proxy for rate limiter behind nginx/docker
app.set('trust proxy', 1);

// Ensure uploads dir exists
const uploadsDir = path.join(__dirname, 'uploads');
fs.mkdirSync(uploadsDir, { recursive: true });

// Middleware — CORS restricted to base domain
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'localhost';
app.use(cors({
  origin: (origin, callback) => {
    if (!origin) return callback(null, true);
    if (origin.includes(BASE_DOMAIN) || origin.includes('localhost')) return callback(null, true);
    callback(null, false);
  },
  credentials: true,
}));
app.use(express.json());

// Rate limiting
const deployLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 5,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many deployments. Please wait a minute.' },
});

// Subdomain routing — skip API and health routes
app.use((req, res, next) => {
  if (req.path.startsWith('/api/') || req.path.startsWith('/health')) return next();
  subdomainMiddleware(req, res, next);
});

// Multer
const upload = multer({
  dest: uploadsDir,
  limits: { fileSize: 50 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    if (file.mimetype === 'application/zip' || file.mimetype === 'application/x-zip-compressed' || file.originalname.endsWith('.zip')) {
      cb(null, true);
    } else {
      cb(new Error('Only ZIP files are allowed'));
    }
  },
});

// Auth rate limiting
const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 20,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many auth attempts. Try again later.' },
});

// Auth routes (public, rate limited)
app.use('/api/auth', authLimiter, authRoutes);
app.use('/health', healthRoutes);

// Public abuse reporting
app.use('/api/report', abuseRoutes);

// Admin routes (protected by ADMIN_SECRET header)
app.use('/api/admin', adminRoutes);

// Wallet suspension check middleware
app.use('/api/deploy', (req, res, next) => {
  if (req.wallet && isWalletSuspended(req.wallet)) {
    return res.status(403).json({ error: 'Your account has been suspended. Contact support.' });
  }
  next();
});

// Protected deploy routes
app.post('/api/deploy', requireAuth, deployLimiter, upload.single('file'), handleDeploy);
app.post('/api/deploy/github', requireAuth, deployLimiter, handleGithubDeploy);
app.get('/api/deploy/logs/:id', streamLogs);

// Protected deployment management
app.get('/api/deployments', requireAuth, listDeployments);
app.delete('/api/deployments/:id', requireAuth, deleteDeployment);
app.get('/api/deployments/:id/versions', requireAuth, listVersions);
app.post('/api/deployments/:id/rollback', requireAuth, rollbackDeployment);

// Custom domain management
app.get('/api/domains', requireAuth, (req, res) => {
  const domains = store.getDomainsByWallet(req.wallet);
  res.json(domains);
});

app.post('/api/domains', requireAuth, (req, res) => {
  const { domain, deploymentId } = req.body;
  if (!domain || !deploymentId) {
    return res.status(400).json({ error: 'Domain and deploymentId are required' });
  }
  // Basic domain validation
  if (!/^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]{2,})+$/.test(domain)) {
    return res.status(400).json({ error: 'Invalid domain format' });
  }
  const deployment = store.get(deploymentId);
  if (!deployment || deployment.wallet !== req.wallet) {
    return res.status(403).json({ error: 'Not authorized' });
  }
  try {
    store.addDomain(domain, deploymentId, req.wallet);

    // Write per-domain vhost config so acme-companion auto-issues SSL cert
    // The LETSENCRYPT_HOST env on nginx-proxy triggers cert issuance for this domain
    const vhostDir = '/etc/nginx/vhost.d';
    const letsencryptEmail = process.env.LETSENCRYPT_EMAIL || 'christopher.dowle@forestinfra.com';
    try {
      if (fs.existsSync(vhostDir)) {
        // Write domain-specific nginx config (enables HSTS, sets proxy headers)
        fs.writeFileSync(
          `${vhostDir}/${domain}`,
          `# Auto-generated by ShelKit for custom domain: ${domain}\nclient_max_body_size 50M;\nproxy_read_timeout 300s;\n`
        );
        // Write LETSENCRYPT_HOST file so acme-companion issues a cert
        fs.writeFileSync(
          `${vhostDir}/${domain}_location`,
          `# ShelKit custom domain\n`
        );
        console.log(`[DOMAIN] Registered ${domain} with nginx-proxy for auto-SSL`);
      }
    } catch (nginxErr) {
      console.warn('[DOMAIN] Could not write vhost config (non-fatal):', nginxErr.message);
    }

    res.json({
      success: true,
      domain,
      deploymentId,
      cname: process.env.BASE_DOMAIN || 'shelkit.forestinfra.com',
      ssl: 'Auto-provisioning SSL certificate — may take a few minutes.',
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

app.delete('/api/domains/:domain', requireAuth, (req, res) => {
  const removed = store.removeDomain(req.params.domain, req.wallet);
  if (!removed) return res.status(404).json({ error: 'Domain not found' });
  res.json({ success: true });
});

// Public — serve deployed sites
app.get('/deploy/:id', serveDeploy);
app.get('/deploy/:id/*', serveDeploy);

// 404 handler for undefined API routes
app.use('/api/*', (req, res) => {
  res.status(404).json({ error: 'API endpoint not found' });
});

// Serve React frontend
const clientDist = path.join(__dirname, '..', 'client', 'dist');
if (fs.existsSync(clientDist)) {
  app.use(express.static(clientDist));
  app.get('*', (req, res) => {
    res.sendFile(path.join(clientDist, 'index.html'));
  });
}

const server = app.listen(PORT, () => {
  console.log(`ShelKit running at http://localhost:${PORT}`);
  console.log(`Shelby: ${process.env.SHELBY_PRIVATE_KEY ? 'live (' + (process.env.SHELBY_NETWORK || 'shelbynet') + ')' : 'stub mode'}`);
  console.log(`Database: SQLite`);
});

// Graceful shutdown
function gracefulShutdown(signal) {
  console.log(`\n${signal} received. Shutting down gracefully...`);
  server.close(() => {
    console.log('Server closed.');
    process.exit(0);
  });
  setTimeout(() => {
    console.error('Forced shutdown after timeout');
    process.exit(1);
  }, 10000);
}
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));
